name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Secrets into HTML
        run: |
          sed -i 's|__PAYTM_MID__|${{ secrets.PAYTM_MID }}|g' index.html
          sed -i 's|__PAYTM_WEBSITE__|${{ secrets.PAYTM_WEBSITE }}|g' index.html
          sed -i 's|__PAYTM_INDUSTRY__|${{ secrets.PAYTM_INDUSTRY }}|g' index.html
          sed -i 's|__PAYTM_CHANNEL__|${{ secrets.PAYTM_CHANNEL }}|g' index.html
          sed -i 's|__PAYTM_KEY__|${{ secrets.PAYTM_KEY }}|g' index.html
          sed -i 's|__GOOGLE_WEB_APP_URL__|${{ secrets.GOOGLE_WEB_APP_URL }}|g' index.html
          sed -i 's|__ADMIN_USERNAME__|${{ secrets.ADMIN_USERNAME }}|g' index.html
          sed -i 's|__ADMIN_PASSWORD__|${{ secrets.ADMIN_PASSWORD }}|g' index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
